### ISSUE TITLE
Bug - Heello dev tool responses returning 401 unauth

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#12]
As on tin. 

https://developer.heello.com/docs/1/GET/users/me - 401
https://developer.heello.com/docs/1/POST/pings/create - 401

May be more.

**Comment by caseym** [comment]
Unable to reproduce, perhaps it's a bad access token or credentials or small service interruption caught at the right time. As of today (4/25 at 2:15 EST), it appears to be working under my account.

**Comment by katanacrimson** [comment]
Just deauthorized and reauthorized again. Still ongoing at this time. 

http://i.imgur.com/0G5EWbM.png

**Comment by katanacrimson** [comment]
Very strange - I've just logged out and back into the developer site, now it's working.  Seems fine now - however judging by the symptoms prior, my gut says that the developer site was thinking it didn't have credentials, since it wasn't allowing me to attempt any of the authenticated endpoints.  Might be a hint for a deeper problem, but I dunno.  

I'm going to close this, but in the future if this comes up again - possible solution is to reauthorize the dev site and log back in afterwards.

**Comment by caseym** [comment]
Thanks, i'll keep any eye on it too.
