### ISSUE TITLE
Feature request - Support usernames as :id for POST/DELETE /users/:id/listen (listen/unlisten)

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#13]
As on tin.  Documentation seems to imply that it's only user ID; if usernames can be used in addition to user ids, can this be clarified?

Reason: As-is, this could result in clients using an additional API query to obtain the user ID for the specified user in order to follow them.

**Comment by caseym** [comment]
This is now enabled for the users/listen and users/unlisten endpoints. Documentation has also been updated.

Include username=1 to indicate the the :id provided in the API Call URL is a username instead of the default assumption that it is a user id.

**Comment by katanacrimson** [comment]
Much thanks @caseym. :)
