### ISSUE TITLE
Documentation - PUT accounts/update - returns updated user object

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#14]
As on tin. This would save a call to /users/me afterwards to obtain updated info at least, as things like avatars will have new URLs that clients cannot predict ahead of time (at least, not that I am aware of).

Relevant endpoint: https://developer.heello.com/docs/1/PUT/accounts/update

**Comment by katanacrimson** [comment]
Looks to be implemented actually. I guess this just needs documented.

**Comment by caseym** [comment]
Has been noted in the response portion of the documentation for the endpoint.
