### ISSUE TITLE
Documentation - PUT accounts/update does not return http 204 on success, returns http 200

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#15]
As on tin. Docs are wrong.

https://developer.heello.com/docs/1/PUT/accounts/update

> On a successul request, a '204 No Content' response is sent.

**Comment by caseym** [comment]
Documentation has been updated to indicate a 200 response as well as indication of the updated user object in the response.

**Comment by katanacrimson** [comment]
Another endpoint is affected: https://developer.heello.com/docs/1/POST/places/create

this one returns http 200 on create it seems, not 201.
