### ISSUE TITLE
Provide API 'changelog'

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#20]
As on tin.  Would have liked to have known about the new endpoints being added.

**Comment by caseym** [comment]
Thanks for the idea, I will add something to the developer site for summarizing changes. Is there anything in particular with it you would find most useful or is just having a list of changes sufficient?

**Comment by katanacrimson** [comment]
Summary and detail are necessary.  Anything BC breaking _MUST_ be noted, and any additions to the API should be noted as well.  Changes (such as http headers, allowing the access_token instead of key for access requests...) should also be documented.  Even if it's just a markdown file that you parse, we _need_ to have communication.

**Comment by caseym** [comment]
https://developer.heello.com/changes

**Comment by katanacrimson** [comment]
Thanks very much! This'll make life a bit easier.
