### ISSUE TITLE
Changing username results in avatar/dp/etc. loss

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#23]
Looks like the idea of basing the avatar upload path on usernames and allowing users to change their usernames is a bad idea. Perhaps it should be based on UIDs to keep things from breaking?

**Comment by caseym** [comment]
There should be a back end process that will move an avatar, cover and background to the new username. Using the username allows clients to predict those resources without the use of an API call.

**Comment by liclac** [comment]
Using the ID would remove the need to predict anything though. Applications should be using the ID as far as possible anyways, as usernames can change at any time, and the user shouldn't have to remove and re-add their account for these changes to take effect (which, sadly, is the case with quite a few Twitter apps…).

**Comment by katanacrimson** [comment]
@caseym in most cases, we'll have the user id anyways from most API calls that involve a user.
