### ISSUE TITLE
Heello developer site privacy policy page

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#26]
![why?](http://i.imgur.com/NzOjPED.png)

...um.

**Comment by caseym** [comment]
@damianb thanks, we'll work on getting some information up soon.

**Comment by caseym** [comment]
Now Available at https://developer.heello.com/privacy

**Comment by katanacrimson** [comment]
Needs some CSS work, it's going off the screen.  Also headers aren't...well, showing properly, I think. 

![http://i.imgur.com/J57w9IQ.png](http://i.imgur.com/J57w9IQ.png)

**Comment by caseym** [comment]
Possible stale css cache in the browser?
![screen shot 2013-06-12 at 3 43 31 pm](https://f.cloud.github.com/assets/507515/645272/cc1f175e-d3a0-11e2-9236-ff0adff8435e.png)

**Comment by liclac** [comment]
Seems like it.
![skarmavbild 2013-06-12 kl 22 47 39](https://f.cloud.github.com/assets/428026/645304/598e47cc-d3a1-11e2-9491-2e62124a24f4.png)

**Comment by katanacrimson** [comment]
DAMN YOU CACHIIIIIIING

**Comment by liclac** [comment]
I should probably also ask you to take a look at that email address under the Copyright section. "heelloinc.com" doesn't have any MX records, and the IP the A record points to doesn't seem reachable, so I imagine delivery would be a bit difficult.

**Comment by caseym** [comment]
Verified delivery works to casey (at) heelloinc.com. 

See:
$ dig mx heelloinc.com

; <<>> DiG 9.8.3-P1 <<>> mx heelloinc.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61370
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;heelloinc.com.         IN  MX

;; ANSWER SECTION:
heelloinc.com.      86400   IN  MX  20 ALT2.ASPMX.L.GOOGLE.com.
heelloinc.com.      86400   IN  MX  30 ASPMX2.GOOGLEMAIL.com.
heelloinc.com.      86400   IN  MX  30 ASPMX3.GOOGLEMAIL.com.
heelloinc.com.      86400   IN  MX  30 ASPMX4.GOOGLEMAIL.com.
heelloinc.com.      86400   IN  MX  30 ASPMX5.GOOGLEMAIL.com.
heelloinc.com.      86400   IN  MX  10 ASPMX.L.GOOGLE.com.
heelloinc.com.      86400   IN  MX  20 ALT1.ASPMX.L.GOOGLE.com.

;; Query time: 162 msec
;; SERVER: 192.168.3.1#53(192.168.3.1)
;; WHEN: Wed Jun 12 17:06:40 2013
;; MSG SIZE  rcvd: 207

**Comment by liclac** [comment]
Oh, wait, I just called dig wrong. Nevermind.
