### ISSUE TITLE
Can't upload image via Heello Web

### ISSUE THREAD

**Issue by liclac** [Heello/Issues#27]
Trying to upload an image ([this one](http://i.imgur.com/en1MPmg.png), more specifically) to Heello landed me on https://heello.com/pings/new, which 404s. Tested in both Chromium and Firefox on a fully updated Arch Linux installation.

**Comment by caseym** [comment]
Will look into. Unable to reproduce thus far on a new session using FF 21.0 on Mac OSX

**Comment by katanacrimson** [comment]
WFM, Win7 x64, FF21 represent.

**Comment by caseym** [comment]
@uppfinnarn Cannot reproduce and haven't heard widespread reports of issues. Please reopen if this is still an issue and we will investigate further.
