### ISSUE TITLE
documentation: /pings/create curl example is for http:// URI to heello API

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#3]
Needs to be adjusted for HTTPS uri, otherwise curl goes full derp.

May affect other endpoints.  Only noticed on /pings/create so far.

**Comment by caseym** [comment]
Fixed on /pings/create and a few other CURL examples as well. 

See: https://developer.heello.com/docs/1/POST/pings/create

Thanks for the heads up!
