### ISSUE TITLE
URL Shortener?

### ISSUE THREAD

**Issue by liclac** [Heello/Issues#31]
A few years ago, Twitter introduced [t.co](http://t.co/), an URL shortener that shortens every link that passes through the service down to 22 characters (23 for HTTPS), while still preserving the original link through means of an Entity node in the Tweet's metadata. The rationale is that the widespread use of URL shorteners (due to links taking up their full length) made clicking links dangerous - you couldn't tell beforehand where you'd end up, save for a couple of clients that offered to "un-shorten" the URL, and even then only for the handful of shortening services that offered un-shortening functionality.

Since t.co was introduced, shortened links are used nearly exclusively by spambots, save for a couple of service-specific ones like [youtu.be](http://youtu.be/) and [d.pr](http://d.pr/), and just-for-fun ones like [waa.ai](http://waa.ai/) (that entire service is a joke about a certain character nobody notices).

To avoid Heello getting into the same situation, an integrated URL shortener on Heello would be very useful.

**Comment by caseym** [comment]
That's a good idea. I think that would be useful too. I'll get it on the roadmap and hopefully we can get a solution in the works.
