### ISSUE TITLE
provide valid "username" regexp for ping parsing

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#34]
As on tin; need to know what characters are valid in a username so I can turn them into auto-links within a client.

**Comment by liclac** [comment]
Possible alternative: Entities node in the metadata marking the ranges in the text to be linked (like how Twitter does it).

**Comment by katanacrimson** [comment]
even then, the valid character ranges would be helpful since we can stop someone from looking up an invalid username without API hits

**Comment by katanacrimson** [comment]
Appears `/[a-z0-9_]/i` is what we've got to work with.  Anything else beyond that or any special rules like no-numerics-first, minimum length, maximum length?

**Comment by caseym** [comment]
/a-zA-Z\d_/

Letters, Numbers and Underscores

Maximum length 18 chars. No limits on minimum length, first character ....

**Comment by katanacrimson** [comment]
wfm, thanks.  Might be worth tossing on the developer site somewhere though.

ed: for reference for anyone in the future: `/([\w]{1,18})/i`

**Comment by caseym** [comment]
Yeah, I'll document it in the documentation.
