### ISSUE TITLE
use HTTP 429 for ping throttling

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#5]
as per RFC 6585, it's the ideal header code, leaving http 503 for its proper use (which is gateway issues).

also, twitter is moving to use 429 too, so it's good for compatibility.

**Comment by caseym** [comment]
I need to look into this a little bit more. With RFC 6585 being a proposed standard I need to do a little more research on the best status code to return.

**Comment by katanacrimson** [comment]
True - though 503 should not be used IMHO, as that is indicative of "ohshit"-class server errors.  The 4xx range would be more appropriate as it indicates that it's a problem with the client or client's request.

**Comment by katanacrimson** [comment]
What's the status of this? Docs seem to indicate that we get a 403 in response now for rate limiting.

ed: And that seems to directly conflict with other pages.

https://developer.heello.com/docs/errors vs https://developer.heello.com/guides/ratelimit

**Comment by katanacrimson** [comment]
Bump...

**Comment by katanacrimson** [comment]
Any updates on this? The lack of clarification here hurts.
