### ISSUE TITLE
SECURITY: heello session cookies not marked "secure" only

### ISSUE THREAD

**Issue by katanacrimson** [Heello/Issues#6]
As on tin. This is dangerous and the cookies should be restricted to HTTPS only.

**Comment by caseym** [comment]
This should be updated either this evening or over the weekend. Thank you for bringing this to our attention.

**Comment by caseym** [comment]
Fixed. Must log out or clear the Heello session cookie to get the new secure cookie.

**Comment by katanacrimson** [comment]
Thanks for the dedication to getting this one fixed.  I'll be poking around and seeing if I can find anything else that is noteworthy.
